### PR TITLE
Uploaded arduino codes, videos, images and simulations.

### PR DESCRIPTION
**Pull request by theobscuredev**

### CODE REVIEW

**Review by SanjeevKrishnan — CHANGES_REQUESTED** [review]
@prady39  Changes Required
1. Add more images in Images and Videos/Images folder
2. Add Solidworks file and their respective snapshots in Mechanical Design folder
3. README.md file is empty. Update it as mentioned in the documentation guideline. 
4. Add poster and report in Poster and Report folder

**Comment by theobscuredev** [comment]
@SanjeevKrishnan @Shubhanshu07 @annushree21 Added cad designs, project report and updated the readme file. We are currently working on the poster and will push it ASAP.

**Review by SanjeevKrishnan — CHANGES_REQUESTED** [review]
@prady39 Changes are required!
1. All snapshots of CAD files have to be present inside respective folders under Mechanical Design folder, not inside Images and Videos/Images
2. Stimulation videos can be placed inside their respective folder. For example, Biped_Bot_Stimulation can be placed inside Mechanical Design/Biped Bot
3. You are not allowed to change the title in README.md. Title should be same as your repo name. In your case "Rube-Goldberg-Machine" it is and it should be of H1 type. Below the title, "Srishti 2020" has to be mentioned as normal text(not heading).
4. In README.md, total cost has to be part of the cost structure table(Line 146)
5. In README.md, Line 148 - Its "Applications", not "Aplications"
6.  Justify the text in the Report. It would be great if you justify the text in README.md too. You can do that with HTML tags.

**Comment by agshubhs** [comment]
@prady39 
1. Try to write single line point. Be precise while writing the point.
2.  Justify the tag using <p> tag of HTML.
3. In report also justify the text.

**Comment by theobscuredev** [comment]
@SanjeevKrishnan  @Shubhanshu07 @annushree21  Necessary changes have been made. Please review from your side.

**Review by SanjeevKrishnan — CHANGES_REQUESTED** [review]
@prady39 Minor Changes are required!
1. Schematic diagram is not required in the poster. Add bot image or full view CAD image.
2. Justify text in README.md

**Comment by agshubhs** [comment]
@prady39 
1, Team members and mentors' names should be in the ordered list.
2.  Unnecessary border is coming in some photos.
3. Poster looks good to me.

**Comment by theobscuredev** [comment]
@SanjeevKrishnan @Shubhanshu07 @annushree21  Suggested changes have been made. Please review from your side.

**Comment by theobscuredev** [comment]
@SanjeevKrishnan @Shubhanshu07 @annushree21 Rectified the border problem with the images.

**Review by SanjeevKrishnan — APPROVED** [review]
@prady39 PR looks fine!
@Shubhanshu07 I suggest for merge.

**Comment by agshubhs** [comment]
@prady39 
Great work guys !!
PR look goods to me also and hence merging it.

**Pull request merged**
